name: Auto Merge Workflow

on:
  push:
    branches:
      - minhal
      - abeeha
      - hammas

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge into main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge --no-ff "${{ github.ref }}"
          git push origin main
